name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          plugin_languages: yes
          plugin_achievements: yes
          plugin_achievements_secrets: yes 
          plugin_achievements_limit: 0
          plugin_isocalendar: yes
          plugin_languages_details: bytes-size, percentage 
          # Your GitHub token
          token: ${{ secrets.SUMMARY_CARDS_TOKEN }}
