name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Line stats plugin
          plugin_lines: yes 
          
          # Stack Overflow plugin
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 3760108                           
          plugin_stackoverflow_sections: answers-top, questions-top 
          plugin_stackoverflow_limit: 3                               
          plugin_stackoverflow_lines: 3   
          
          # WakaTime plugin
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}      
          plugin_wakatime_days: 365                                  
          plugin_wakatime_sections: time, languates, languages-graphs, editors, editors-graph, os, os-graph
          plugin_wakatime_limit: 6   
          
          # Languages plugin
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage 
          
          # Achievements plugin
          plugin_achievements: yes
          plugin_achievements_secrets: yes 
          plugin_achievements_limit: 0
          
          # Recent activity plugin
          plugin_activity: yes
          plugin_activity_limit: 5    # Limit to 5 events
          plugin_activity_days: 0
          plugin_activity_filter: all # Show all events (use table above to filter events types)
          
          # Isocalendar plugin
          plugin_isocalendar: yes
          
          # GitHub token
          token: ${{ secrets.SUMMARY_CARDS_TOKEN }}
