name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Line stats plugin
          plugin_lines: yes 
          
          # Stack Overflow plugin
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 3760108                           
          plugin_stackoverflow_sections: questions-top, answers-top
          plugin_stackoverflow_limit: 3                               
          plugin_stackoverflow_lines: 2   
          
          # Notable contributions <- Not yet useful for me...
          # plugin_notable: yes
          # plugin_notable_repositories: yes 
          
          # Languages plugin
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage 
          
          # Achievements plugin
          plugin_achievements: yes
          plugin_achievements_secrets: yes 
          plugin_achievements_limit: 0
          
          # Recent activity plugin
          plugin_activity: yes
          plugin_activity_limit: 7
          plugin_activity_days: 0
          plugin_activity_filter: release, issue, pr, review, fork, public, ref/create, ref/delete, wiki
          
          # Isocalendar plugin
          plugin_isocalendar: yes
          
          # GitHub token
          token: ${{ secrets.SUMMARY_CARDS_TOKEN }}
